In [1]:
import pandas as pd
pd.version.version

'0.13.1'

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-24-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: ja_JP.UTF-8

pandas: 0.13.1
Cython: None
numpy: 1.8.2
scipy: 0.13.3
statsmodels: 0.5.0
IPython: 4.0.0
sphinx: None
patsy: 0.2.1
scikits.timeseries: None
dateutil: 1.5
pytz: 2012c
bottleneck: None
tables: 3.1.1
numexpr: 2.2.2
matplotlib: 1.3.1
openpyxl: 1.7.0
xlrd: 0.9.2
xlwt: 0.7.5
xlsxwriter: None
sqlalchemy: None
lxml: 3.3.3
bs4: 4.2.1
html5lib: 0.999
bq: None
apiclient: None


In [18]:
#ndarray オンリーにして書いてるのですが，行列同士を np.dot で掛けると
#行列積になるけど，自動で転置をしてくれる
#自動で転置をするのは片方がベクトル(１次元)の時だけで
#両方が行列（２次元）の場合は、明示的に第１項の列数と第２項の行数をあわせないとエラーになります

import numpy as np
c = np.arange(1,5).reshape(2,2)
d = np.arange(2)
print "c , d\n", c, "\n", d
print "c * d\n", c * d
print "c * d.T\n", c * d.T
print "c * d.reshape(1,2)\n", c * d.reshape(1,2)
print "c * d.reshape(2,1)\n", c * d.reshape(2,1)
print "c* np.atleast_2d(d).T\n", c* np.atleast_2d(d).T
print "c * d[:, np.newaxis]\n", c * d[:, np.newaxis]

c , d
[[1 2]
 [3 4]] 
[0 1]
c * d
[[0 2]
 [0 4]]
c * d.T
[[0 2]
 [0 4]]
c * d.reshape(1,2)
[[0 2]
 [0 4]]
c * d.reshape(2,1)
[[0 0]
 [3 4]]
c* np.atleast_2d(d).T
[[0 0]
 [3 4]]
c * d[:, np.newaxis]
[[0 0]
 [3 4]]
